version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20  # Specify the Node.js version you want
    image: junkbazzar_bazar_vendor_app
    ports:
      - "3000:3000"
      # - "5001:5000"
      # - "5002:5000"
    deploy:
      replicas: 1
networks:
  junknetwork:
    driver: bazzar